// Full inventory catalog from the official "Branch Inventory" form.
// Single source of truth used by `prisma/seed.ts` (fresh seed) and
// `prisma/seed-inventory-catalog.ts` (idempotent sync into an existing DB).

export interface InventoryCatalogCategory {
  name: string;
  sortOrder: number;
  items: string[];
}

export const INVENTORY_CATALOG: InventoryCatalogCategory[] = [
  {
    name: "Chinaware",
    sortOrder: 1,
    items: [
      "Rice dish",
      "Service plate",
      "Dinner plate Round",
      "Dinner Plate Square",
      "Soup liner",
      "Small soup bowl",
      "Big soup bowl",
      "Table soup cup",
      "BBQ Plate",
      "Sauce set",
      "Salt & pepper set",
      "Soya sauce bottle",
      "Tea cup",
      "Tea pot",
      "Sugar pot",
      "Sugar Bowl",
      "Milk pot",
      "Ice cream cup",
      "Tea saucer",
      "Sauce Bowl",
      "Flower vase",
      "Finger bowl",
      "Toothpick Holder",
    ],
  },
  {
    name: "Glassware",
    sortOrder: 2,
    items: [
      "Tumbler",
      "High Ball Glass / Pilsner",
      "Water Goblet Glass",
      "Welcome Drink glass",
      "Borhani Glass",
      "Borhani Jug",
      "Juice Glass",
    ],
  },
  {
    name: "Linen",
    sortOrder: 3,
    items: ["Table cloth/Nap", "Table Tops / Napron", "Cloth Napkin"],
  },
  {
    name: "Cutlery",
    sortOrder: 4,
    items: [
      "Table spoon",
      "Table fork",
      "Table knife",
      "Steak Knife",
      "Soup ladle",
      "Service spoon",
      "Service soup spoon",
      "Tea spoon",
      "Sauce spoon",
    ],
  },
  {
    name: "Holloware",
    sortOrder: 5,
    items: [
      "Steam boat pot",
      "Chop stick",
      "Long tray",
      "Round tray",
      "Soft tray",
      "Chef-in-dish",
      "Sizzling dish",
      "Fish Tray",
      "Glass rack",
      "Spoon Case",
    ],
  },
  {
    name: "Other",
    sortOrder: 6,
    items: [
      "Sofa (All)",
      "Cane Partition",
      "Chair All",
      "Baby chair",
      "Office chair",
      "Table",
      "Office table",
      "Almirah (steel/wood)",
      "Deep fridge",
      "Normal fridge",
      "Ice cream fridge",
      "Mixer Machine",
      "Meat Grinder",
      "Plate Warmer",
      "Incubator",
      "Ice Maker",
      "Gas Burner",
      "Grill Machine",
      "Induction Cooker",
      "Oven",
      "Dishwasher Machine",
      "Noodles machine",
      "Juice machine",
      "Water Filter",
      "Spa Chair",
      "Aquarium",
      "Computer",
      "Printer",
      "Scanner",
      "Weight Scale",
      "Telephone set",
      "Mobile set",
      "Mobile SIM",
      "PABX set",
      "DVD player",
      "Amplifier",
      "Speaker",
      "TV",
      "Internet router",
      "Attendance device",
      "CC camera",
      "CC camera set (DVR)",
      "Walkie Talkie Set",
      "Neon sign",
      "Hot Pot (warmer)",
      "Sub Station",
      "Generator",
      "Lift",
      "AC, 5 ton",
      "AC, 3 ton",
      "AC, 1.5 ton",
      "AC, window",
      "Air Cutter",
      "Exhaust Fan",
      "Stand fan",
      "Fan (Ceiling and Wall)",
      "Tube Light",
      "Ice Bucket",
      "Jhar bati",
    ],
  },
  {
    name: "Bangla Party Equipment",
    sortOrder: 7,
    items: [
      "Bangla Handi (all sizes)",
      "Bangla Koroy",
      "Bangla Logon",
      "Bangla Small bowl",
      "Bangla rice dish",
      "Bangla curry bowl",
      "Bangla service plate",
      "Bangla rice spoon",
      "Handi",
      "Koroy",
      "Chapati",
      "Kitchen knife",
      "Kitchen big dabbu",
      "Kitchen big spoon",
      "Kitchen Table SS",
      "Reserved board",
      "Kitchen Trolley",
    ],
  },
  {
    name: "Beverage Corner",
    sortOrder: 8,
    items: [
      "Coffee Machine",
      "Coffee Grinder",
      "Coffee Cup",
      "Coffee Saucer",
      "Cake tray",
      "Cake Mould",
      "Cake Table",
      "Container",
      "Chopping Board",
      "Coffee Mug",
      "Display Freezer",
      "Dessert Plate (Small Size)",
      "Date Seal Pad",
      "Dessert Spoon",
      "Espresso Cup",
      "Espresso Saucer",
      "Grater",
      "Hand Mixer Machine",
      "Hand Wash Pot",
      "Hand Wiks",
      "Ice Blender",
      "Induction Cooker",
      "Icer Breaker Hammer",
      "Ice Cream Scoop",
      "Knock Box",
      "Knife",
      "Long Spoon",
      "Milk Pitcher",
      "Mahlabiya Cup",
      "Margarita Glass",
      "Electric Oven",
      "Plate Knife",
      "Pump",
      "Scissors",
      "Sticel Pot",
      "Stifler",
      "Strainer",
      "Skaper",
      "Small Refrigeration",
      "Steel Handi",
      "Tamper mat",
      "Tank",
      "Tape Holder",
      "Weight Scale",
      "Water Softener",
      "Wooden Tamper",
    ],
  },
];
